package main;

import helper.MessageDialogHelper;
import helper.ShareHelper;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicButtonUI;
import model.User;
import views.Home;
import views.Info;
import views.Loadding;
import views.Login;
import views.ManagerGrade;
import views.ManagerUser;

/**
 *
 * @author ACER
 */
public class Main extends javax.swing.JFrame {

    private JPanel childJPanel;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        enventButton();
        loadding();
        login();
        childJPanel = new Home();
        openJPanel(childJPanel);
    }

    //Xử lý sự kiến nút button
    private void enventButton() {
        JButton[] btns = {btnHome, btnExit, btnLogout, btnInfo, btnManagerUser, btnManagerPoint};
        for (JButton btn : btns) {
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    btn.setBackground(new Color(0, 102, 153));
                    User entity = ShareHelper.USER;
                    String cmd = btn.getActionCommand();
                    switch (cmd) {
                        case "Exit":
                            if (MessageDialogHelper.showComfirmDialog(jPanelViews, "Bạn có muốn thoát chương trình không ?", "Thoát chương trình")
                                    == JOptionPane.YES_OPTION) {
                                System.exit(0);
                            }
                            break;
                        case "ManagerUser":
                            if (entity.getVaiTro() == 1) {
                                childJPanel = new ManagerUser();
                            } else {
                                MessageDialogHelper.showErrorDialog(jPanelViews, "Chỉ có cán bộ đào tạo mới quản lý sinh viên !", "Lỗi");
                            }
                            break;
                        case "ManagerGrade":
                            if (entity.getVaiTro() == 0) {
                                childJPanel = new ManagerGrade();
                            } else {
                                MessageDialogHelper.showErrorDialog(jPanelViews, "Chỉ có giảng viên mới cập nhập điểm !", "Lỗi");
                            }
                            break;
                        case "Home":
                            childJPanel = new Home();
                            break;
                            case "Info":
                            new Info().setVisible(true);
                            break;
                        case "LogOut":
                            if (MessageDialogHelper.showComfirmDialog(jPanelViews, "Bạn có muốn đăng xuất ?", "Đăng xuất")
                                    == JOptionPane.YES_OPTION) {
                                if (ShareHelper.logoff() == true) {
                                    dispose();
                                    Main main = new Main();
                                    main.setVisible(true);
                                }
                            }
                            break;
                    }
                    openJPanel(childJPanel);
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    btn.setBackground(new Color(102, 204, 5));
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    btn.setBackground(new Color(102, 204, 5));
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(102, 204, 255));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(0, 102, 0));
                }
            });
        }
    }

    //Phương thức mở jpanel
    private void openJPanel(JPanel childJPanel) {
        jPanelViews.removeAll();
        jPanelViews.add(childJPanel);
        jPanelViews.validate();
        jPanelViews.repaint();
    }

    //Phương thức mở login khi mở ứng dụng
    private void loadding() {
        new Loadding(this, true).setVisible(true);
    }

    private void login() {
        new Login(this, true).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnInfo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnManagerUser = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnManagerPoint = new javax.swing.JButton();
        jPanelViews = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 770));
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(80, 770));
        jPanel2.setMinimumSize(new java.awt.Dimension(80, 770));
        jPanel2.setPreferredSize(new java.awt.Dimension(80, 770));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 60));

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(50, 50));
        jPanel4.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        btnHome.setBackground(new java.awt.Color(0, 102, 0));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_home_50px.png"))); // NOI18N
        btnHome.setActionCommand("Home");
        btnHome.setBorder(null);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(btnHome, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 102, 0));
        jPanel5.setMaximumSize(new java.awt.Dimension(50, 50));
        jPanel5.setLayout(new java.awt.BorderLayout());

        btnLogout.setBackground(new java.awt.Color(0, 102, 0));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Logout_50px.png"))); // NOI18N
        btnLogout.setActionCommand("LogOut");
        btnLogout.setBorder(null);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(btnLogout, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(0, 102, 0));
        jPanel6.setMaximumSize(new java.awt.Dimension(50, 50));
        jPanel6.setLayout(new java.awt.BorderLayout());

        btnExit.setBackground(new java.awt.Color(0, 102, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_imac_exit_50px.png"))); // NOI18N
        btnExit.setActionCommand("Exit");
        btnExit.setBorder(null);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(btnExit, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 102, 0));
        jPanel7.setMaximumSize(new java.awt.Dimension(50, 50));
        jPanel7.setLayout(new java.awt.BorderLayout());

        btnInfo.setBackground(new java.awt.Color(0, 102, 0));
        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_info_50px.png"))); // NOI18N
        btnInfo.setActionCommand("Info");
        btnInfo.setBorder(null);
        btnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(btnInfo, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(0, 102, 0));
        jPanel8.setMaximumSize(new java.awt.Dimension(50, 50));
        jPanel8.setLayout(new java.awt.BorderLayout());

        btnManagerUser.setBackground(new java.awt.Color(0, 102, 0));
        btnManagerUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_management_50px.png"))); // NOI18N
        btnManagerUser.setActionCommand("ManagerUser");
        btnManagerUser.setBorder(null);
        btnManagerUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(btnManagerUser, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(0, 102, 0));
        jPanel9.setMaximumSize(new java.awt.Dimension(50, 50));
        jPanel9.setLayout(new java.awt.BorderLayout());

        btnManagerPoint.setBackground(new java.awt.Color(0, 102, 0));
        btnManagerPoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_pen_50px.png"))); // NOI18N
        btnManagerPoint.setActionCommand("ManagerGrade");
        btnManagerPoint.setBorder(null);
        btnManagerPoint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.add(btnManagerPoint, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9);

        getContentPane().add(jPanel2);

        jPanelViews.setBackground(new java.awt.Color(0, 102, 0));
        jPanelViews.setMaximumSize(new java.awt.Dimension(1220, 770));
        jPanelViews.setMinimumSize(new java.awt.Dimension(1220, 770));
        jPanelViews.setPreferredSize(new java.awt.Dimension(1220, 770));
        jPanelViews.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanelViews);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManagerPoint;
    private javax.swing.JButton btnManagerUser;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelViews;
    // End of variables declaration//GEN-END:variables
}
