package views;

import dao.UserDao;
import helper.DataValidator;
import helper.MessageDialogHelper;
import helper.ShareHelper;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.TimerTask;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;
import main.Main;
import model.User;

/**
 *
 * @author ACER
 */
public class Login extends javax.swing.JDialog {

    /**
     * Creates new form LoginJDialog
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        enventButton();
        jPanelLogin.setVisible(true);
        jPanelLoad.setVisible(false);
    }

    //Xử lý sự kiến nút button
    private void enventButton() {
        JButton[] btns = {btnExit, btnLogin};
        for (JButton btn : btns) {
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    btn.setBackground(new Color(0, 102, 153));
                    String cmd = btn.getActionCommand();
                    switch (cmd) {
                        case "Login":
                            login();
                            break;
                        case "Exit":
                            exit();
                            break;
                    }
                }
                
                @Override
                public void mousePressed(MouseEvent e) {
                    btn.setBackground(new Color(102, 204, 5));
                }
                
                @Override
                public void mouseReleased(MouseEvent e) {
                    btn.setBackground(new Color(102, 204, 5));
                }
                
                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(102, 204, 255));
                }
                
                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(0, 102, 0));
                }
            });
        }
    }

    //Phương thức đăng nhập
    private void login() {
        try {
            StringBuilder sb = new StringBuilder();
            DataValidator.validateEmpty(txtUserName, sb, "Tên đăng nhập không được để trống !");
            DataValidator.validateEmpty(txtPass, sb, "Mật khẩu không được để trống !");
            if (sb.length() > 0) {
                MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            } else {
                String email = txtUserName.getText();
                String pass = new String(txtPass.getPassword());
                UserDao dao = new UserDao();
                User entity = dao.checkLogin(email, pass);
                if (entity == null) {
                    MessageDialogHelper.showErrorDialog(this, "Tên đăng nhập hoặc mật khẩu sai !", "Sai nhập liệu");
                    reset();
                } else {
                    MessageDialogHelper.showMessageDialog(this, "Bạn đã đăng nhập thành công ", "Thông báo");
                    ShareHelper.USER = entity;
                    String chucVu = "Cán bộ đào tạo";
                    if (entity.getVaiTro() == 0) {
                        chucVu = "Giảng viên";
                    }
                    MessageDialogHelper.showMessageDialog(this, "Xin chào " + entity.getTenDangNhap() + " - " + chucVu, "Xin chào");
                    jPanelLogin.setVisible(false);
                    jPanelLoad.setVisible(true);
                    new java.util.Timer().schedule(new TimerTask() {
                        @Override
                        public void run() {
                            dispose();
                        }
                    }, 1000 * 10);
                }
            }
        } catch (Exception e) {
            System.out.println("->Login(login) - " + e);
        }
    }
    //Phương thức làm mới

    private void reset() {
        txtUserName.setText("");
        txtPass.setText("");
        txtUserName.setBackground(new Color(0, 102, 0));
        txtPass.setBackground(new Color(0, 102, 0));
    }

    //Phương thức thoát
    private void exit() {
        if (MessageDialogHelper.showComfirmDialog(this, "Bạn có muốn thoát chương trình không ?", "Thoát chương trình")
                == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtUserName = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPass = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanelLoad = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelLogin.setBackground(new java.awt.Color(0, 102, 0));
        jPanelLogin.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanelLogin.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanelLogin.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelLogin.setLayout(new javax.swing.BoxLayout(jPanelLogin, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));
        jPanel3.setMaximumSize(new java.awt.Dimension(836, 100));
        jPanel3.setMinimumSize(new java.awt.Dimension(836, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(836, 100));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG NHẬP");
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanelLogin.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(529, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(529, 100));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setBackground(new java.awt.Color(0, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_name_50px.png"))); // NOI18N
        jPanel1.add(jLabel2);

        jPanel8.setBackground(new java.awt.Color(0, 102, 0));
        jPanel8.setMaximumSize(new java.awt.Dimension(479, 80));
        jPanel8.setMinimumSize(new java.awt.Dimension(479, 80));
        jPanel8.setPreferredSize(new java.awt.Dimension(479, 80));
        jPanel8.setLayout(new java.awt.BorderLayout(0, 5));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jSeparator1, java.awt.BorderLayout.CENTER);

        txtUserName.setBackground(new java.awt.Color(0, 102, 0));
        txtUserName.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(0, 0, 0));
        txtUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserName.setText("admin");
        txtUserName.setBorder(null);
        txtUserName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUserName.setMaximumSize(new java.awt.Dimension(310, 60));
        txtUserName.setMinimumSize(new java.awt.Dimension(310, 60));
        txtUserName.setPreferredSize(new java.awt.Dimension(310, 60));
        jPanel8.add(txtUserName, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel8);

        jPanel4.add(jPanel1);

        jPanelLogin.add(jPanel4);

        jPanel9.setBackground(new java.awt.Color(0, 102, 0));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));

        jPanel10.setBackground(new java.awt.Color(0, 102, 0));
        jPanel10.setMaximumSize(new java.awt.Dimension(529, 100));
        jPanel10.setMinimumSize(new java.awt.Dimension(529, 100));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setBackground(new java.awt.Color(0, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_password_reset_50px.png"))); // NOI18N
        jPanel10.add(jLabel3);

        jPanel11.setBackground(new java.awt.Color(0, 102, 0));
        jPanel11.setMaximumSize(new java.awt.Dimension(479, 80));
        jPanel11.setMinimumSize(new java.awt.Dimension(479, 80));
        jPanel11.setPreferredSize(new java.awt.Dimension(479, 80));
        jPanel11.setLayout(new java.awt.BorderLayout(0, 5));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.add(jSeparator2, java.awt.BorderLayout.CENTER);

        txtPass.setBackground(new java.awt.Color(0, 102, 0));
        txtPass.setFont(new java.awt.Font("Curlz MT", 1, 36)); // NOI18N
        txtPass.setForeground(new java.awt.Color(0, 0, 0));
        txtPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPass.setText("admin");
        txtPass.setBorder(null);
        txtPass.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPass.setMaximumSize(new java.awt.Dimension(310, 60));
        txtPass.setMinimumSize(new java.awt.Dimension(310, 60));
        txtPass.setPreferredSize(new java.awt.Dimension(310, 60));
        jPanel11.add(txtPass, java.awt.BorderLayout.PAGE_START);

        jPanel10.add(jPanel11);

        jPanel9.add(jPanel10);

        jPanelLogin.add(jPanel9);

        jPanel7.setBackground(new java.awt.Color(0, 102, 0));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 35));

        btnLogin.setBackground(new java.awt.Color(0, 102, 0));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_login_50px.png"))); // NOI18N
        btnLogin.setActionCommand("Login");
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(btnLogin);

        btnExit.setBackground(new java.awt.Color(0, 102, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_exit_sign_50px.png"))); // NOI18N
        btnExit.setActionCommand("Exit");
        btnExit.setBorder(null);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(btnExit);

        jPanelLogin.add(jPanel7);

        getContentPane().add(jPanelLogin, "card2");

        jPanelLoad.setBackground(new java.awt.Color(0, 102, 0));
        jPanelLoad.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanelLoad.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/E V I L ▪ G A M E.gif"))); // NOI18N
        jPanelLoad.add(jLabel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelLoad, "card3");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelLoad;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
